---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-perf-test-dp-sandbox
  namespace: kafka-self-hosted-perf-test
  labels:
    app: consumer-perf-test-dp-sandbox
    k2.segment.com/app: consumer-perf-test-dp-sandbox
    k2.segment.com/argocd: "true"
    k2.segment.com/build: 7f0d713
    k2.segment.com/deploy: a95f9852384c46
    k2.segment.com/repo: smsk-kafka-load
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
    version: 7f0d713-a95f9852384c46
  annotations:
    k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/consumer-perf-test-dp-sandbox.yaml","appName":"consumer-perf-test-dp-sandbox","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"7f0d713","deployID":"a95f9852384c46","deployTime":"2022-12-05T07:05:15.248183Z","fullDiffs":false,"host":"V50WMJ429K","image":null,"k2Root":"/Users/rsaiprasanna/.kube/k2","k2Version":"1.3.0","repoBranch":"deploy-consumer","repoName":"smsk-kafka-load","repoSHA":"75dd29c4e9f5555955328421c8d4bf632b27f980","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"stage","user":"rsaiprasanna","workingDir":"/Users/rsaiprasanna/Desktop/exp/add_conusmer_smsk_dp/smsk-kafka-load","shardDeployment":false}'
spec:
  strategy:
    {}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: consumer-perf-test-dp-sandbox
  template:
    metadata:
      labels:
        app: consumer-perf-test-dp-sandbox
        k2.segment.com/app: consumer-perf-test-dp-sandbox
        k2.segment.com/argocd: "true"
        k2.segment.com/build: 7f0d713
        k2.segment.com/deploy: a95f9852384c46
        k2.segment.com/repo: smsk-kafka-load
        k2.segment.com/skipped-checks: "true"
        segment.com/managed-by: k2
        version: 7f0d713-a95f9852384c46
      annotations:
        k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/consumer-perf-test-dp-sandbox.yaml","appName":"consumer-perf-test-dp-sandbox","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"7f0d713","deployID":"a95f9852384c46","deployTime":"2022-12-05T07:05:15.248183Z","fullDiffs":false,"host":"V50WMJ429K","image":null,"k2Root":"/Users/rsaiprasanna/.kube/k2","k2Version":"1.3.0","repoBranch":"deploy-consumer","repoName":"smsk-kafka-load","repoSHA":"75dd29c4e9f5555955328421c8d4bf632b27f980","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"stage","user":"rsaiprasanna","workingDir":"/Users/rsaiprasanna/Desktop/exp/add_conusmer_smsk_dp/smsk-kafka-load","shardDeployment":false}'
      name: consumer-perf-test-dp-sandbox
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 169.254.20.10
        searches:
        - kafka-self-hosted-perf-test.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - us-west-2.compute.internal
        options:
        - name: ndot
          value: '2'
      serviceAccountName: consumer-perf-test-dp-sandbox
      nodeSelector:
        segment.com/pool: producer_consumer
      containers:
      - command:
        - /srv/kafka/bin/kafka-console-consumer.sh
        - --topic
        - topic-test-1
        - --group
        - smsk-consumer-1
        - --bootstrap-server=kafka-kafka-self-hosted-perf-test.dp-sandbox.segment.local:9092
        - --from-beginning
        env:
        - name: ACCOUNT_ALIAS
          value: stage
        - name: ENVIRONMENT
          value: stage
        - name: GOMAXPROCS
          value: "1"
        - name: K8S_CONTAINER_NAME
          value: consumer-perf-test-dp-sandbox
        - name: K8S_DEPLOYMENT
          value: consumer-perf-test-dp-sandbox
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SEGMENT_CELL
          value: core
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-kafka-load:v2.8.1
        name: consumer-perf-test-dp-sandbox
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: consumer-perf-test-dp-sandbox
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes: