# deploy - k2 deploy app producer-stage-usw2-dp-sandbox -t producer-stage-usw2-dp-sandbox -b <build> --argocd --skip-checks
# delete - k2 delete app producer-stage-usw2-dp-sandbox -t producer-stage-usw2-dp-sandbox
apiVersion: platform.segment.com/v1alpha1
kind: SegmentApplicationExperimental
cell: core
metadata:
  name: producer3-perf-test-dp-sandbox
  namespace: kafka-self-hosted-perf-test
spec:
  targets:
  - name: stage
    cluster: stage:us-west-2:dp-sandbox
    pool: producer_consumer
    replicatedService:
      iamRoleName: kafka-self-hosted-perf-test
      namespace: kafka-self-hosted-perf-test
      replicas: 50
      mainContainer:
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-kafka-load:v2.8.1
        command:
        - "/srv/kafka/bin/kafka-producer-perf-test.sh"
        - "--topic"
        - "topic-test-1"
        - "--num-records"
        - "100000000000"
        - "--throughput"
        - "375000"
        - "--producer-props"
        - "bootstrap.servers=kafka-kafka-self-hosted-perf-test.dp-sandbox.segment.local:9092"
        - "compression.type=zstd"
        - "buffer.memory=67108864"
        - "batch.size=20000000"
        - "linger.ms=15"
        - "--record-size"
        - "16000"
        resources:
          limits:
            cpu: 2
            memory: 0.5Gi
        ctlstore:
          disabled: true
