apiVersion: platform.segment.com/v1alpha1
kind: SegmentApplicationExperimental
cell: core
metadata:
  name: smsk-kafka-load-producer
  namespace: psm-stage-usw2-load-test
spec:
  targets:
  - name: producer-stage-usw2-personas
    cluster: stage:us-west-2:personas
    replicatedService:
      iamRoleName: smsk-kafka-load-producer
      namespace: psm-stage-usw2-load-test
      replicas: 1
      mainContainer:
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-kafka-load:v2.5.1
        command:
        - "/srv/kafka/bin/kafka-producer-perf-test.sh"
        - "--topic"
        - "test-1"
        - "--num-records"
        - "100000000"
        - "--throughput"
        - "30000"
        - "--producer-props"
        - "bootstrap.servers=kafka-kafka-personas.personas.segment.local:9092"
        - "--record-size"
        - "100"
        resources:
          limits:
            cpu: 0.5
            memory: 256M
        ctlstore:
          disabled: true
