apiVersion: platform.segment.com/v1alpha1
kind: SegmentApplicationExperimental
cell: core
metadata:
  name: smsk-kafka-load-producer
  namespace: smsk-kafka-test
spec:
  targets:
  - name: producer-prod-usw2-personas
    cluster: production:us-west-2:personas
    replicatedService:
      iamRoleName: smsk-kafka-load-producer
      namespace: smsk-kafka-test
      replicas: 1
      mainContainer:
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-kafka-load:v2.5.1
        imageName: smsk-kafka-load
        imageRegistry: 528451384384.dkr.ecr.us-west-2.amazonaws.com
        command:
        - "/srv/kafka/bin/kafka-producer-perf-test.sh"
        - "--topic"
        - "test-1"
        - "--num-records"
        - "10000000"
        - "--throughput"
        - "10000"
        - "--producer-props"
        - "bootstrap.servers=kafka-kafka-personas.personas.segment.local:9092"
        - "--record-size"
        - "50"
        resources:
          limits:
            cpu: 1
            memory: 256M
        ctlstore:
          disabled: true
