apiVersion: platform.segment.com/v1alpha1
kind: SegmentApplicationExperimental
cell: core
metadata:
  name: smsk-kafka-load-producer
  namespace: smsk-kafka-load
spec:
  targets:
  - name: producer-stage-usw2-dp-sandbox
    cluster: stage:us-west-2:dp-sandbox
    replicatedService:
      iamRoleName: smsk-kafka-load-producer
      namespace: smsk-kafka-load
      replicas: 1
      mainContainer:
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-kafka-load:v2.5.1
        imageName: smsk-kafka-load
        imageRegistry: 528451384384.dkr.ecr.us-west-2.amazonaws.com
        command:
        - "/srv/kafka/bin/kafka-producer-perf-test.sh"
        - "--topic"
        - "test-1"
        - "--num-records"
        - "1000000"
        - "--throughput"
        - "100"
        - "--producer-props"
        - "bootstrap.servers=kafka-kafka.dp-sandbox.segment.local:9092"
        - "--record-size"
        - "50"
        resources:
          limits:
            cpu: 0.25
            memory: 128M
        ctlstore:
          disabled: true
