---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: producer2-perf-test-dp-sandbox
  namespace: kafka-self-hosted-perf-test
  labels:
    app: producer2-perf-test-dp-sandbox
    k2.segment.com/app: producer2-perf-test-dp-sandbox
    k2.segment.com/repo: smsk-kafka-load
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: producer2-perf-test-dp-sandbox
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75